### ISSUE TITLE
two or more params for faker aren't supported

### ISSUE THREAD

**Issue by mishelen** [RobinCK/typeorm-fixtures#103]
Seems that  I can use such definition:

```yaml
entity: Ring
items:
  ring{0..10}:
    date: '{{date.past(5, '2018-01-01')}}'
```

because this method gets only one param which is `5, '2018-01-01'`
