### ISSUE TITLE
Literal double curly braces not possible due to faker parser

### ISSUE THREAD

**Issue by matomesc** [RobinCK/typeorm-fixtures#117]
Due to https://github.com/RobinCK/typeorm-fixtures/blob/master/src/parsers/FakerParser.ts#L15 it's impossible to have a string with literal double curly, for example:

```
entity: User
items:
  user0:
    comment: 'here is a liquid template {{ my_variable }}'
``` 

will fail to build with a `Invalid module: my_variable` exception thrown by `faker`.

**Comment by RobinCK** [comment]
you can try using postprocessor to cast the string to your format
```
entity: User
items:
  user0:
    comment: 'here is a liquid template [[ my_variable ]]'
```

and in postprocessor replaced to {{ ... }}
