### ISSUE TITLE
[Bug] "fixtures" command not found

### ISSUE THREAD

**Issue by joelclouddistrict** [RobinCK/typeorm-fixtures#127]
I have installed this package following the documentation with:

``` bash
npm install typeorm-fixtures-cli --save-dev
```
I also have created a fixture file in `fixtures/User.yml` with:

``` yaml
entity: User
items:
    user1:
        username: 'user@example.org'
```
But when I try to run the `fixtures` command I get a `command not found error`

``` bash
root@ed0c1271ba48:/application# fixtures
bash: fixtures: command not found
```

I am running this on a `node:12.16.2` Docker image

Do I need to do anything else after installing the package?

Thank you very much.
