### ISSUE TITLE
[Bug] TypeOrm Lazy relations are not properly handled

### ISSUE THREAD

**Issue by ygarris** [RobinCK/typeorm-fixtures#143]
If you have relations defined as lazy, i.e. like:
```
@Entity()
class User {
  @OneToOne('Profile', 'user')
  profile: Promise<Profile>
}
```
Then when you run fixtures - all relation fields are nulls.
No exceptions thrown during fixtures loading.

TypeOrm Lazy Relations doc: https://typeorm.io/#/eager-and-lazy-relations/lazy-relations

### Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| typeorm | 0.2.25 |
| typeorm-fixtures | 1.6.0 |
| Node             | v12.16.3 |
| npm/Yarn         | 6.14.5 |
| Operating System | Linux |

**Comment by ygarris** [comment]
Hey @RobinCK ,
I tried to find a workaround by using processors, but it's not working, too.

`account.yaml`:
```yaml
entity: Account
processor: processors/account.processor.ts
items:
  account1:
    app: test_app
    roles:
      - user
    user: '@user1'
```

`processors/account.processor.ts`:
```typescript
import { IProcessor } from 'typeorm-fixtures-cli/dist';
import { Account } from '../../src/account';

export default class AccountProcessor implements IProcessor<Account>{
  preProcess(name: string, object: Account): any {
    object.user = Promise.resolve(object.user);
    return object;
  }
}
```
Account table still has `userId` set to `null`.
