### ISSUE TITLE
How to set embedded values?

### ISSUE THREAD

**Issue by brussee** [RobinCK/typeorm-fixtures#145]
| Software         | Version(s) |
| ---------------- | ---------- |
| typeorm-fixtures | 1.7.0 |
| Node             | 14.4.0 |
| Yarn         | 1.22.4 |
| Operating System | Debian 10 |

```
$ node -r tsconfig-paths/register -r ts-node/register node_modules/.bin/fixtures --config ./apps/my-api/src/db.config.ts --sync ./fixtures
Progress  [██████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░] 20% | ETA: 1s | 1/5 user1 
Fail fixture loading: entity[propertyPath][this.propertyName] is not a function
TypeError: entity[propertyPath][this.propertyName] is not a function
    at EntityListenerMetadata.callEntityEmbeddedMethod (/nest-pkgs/src/metadata/EntityListenerMetadata.ts:89:52)
    at EntityListenerMetadata.execute (/nest-pkgs/src/metadata/EntityListenerMetadata.ts:73:14)
    at /nest-pkgs/src/subscriber/Broadcaster.ts:38:54
    at Array.forEach (<anonymous>)
    at Broadcaster.broadcastBeforeInsertEvent (/nest-pkgs/src/subscriber/Broadcaster.ts:36:44)
    at /nest-pkgs/src/persistence/SubjectExecutor.ts:211:81
    at Array.forEach (<anonymous>)
    at SubjectExecutor.broadcastBeforeEventsForAll (/nest-pkgs/src/persistence/SubjectExecutor.ts:211:33)
    at SubjectExecutor.<anonymous> (/nest-pkgs/src/persistence/SubjectExecutor.ts:108:38)
    at step (/nest-pkgs/node_modules/typeorm/node_modules/tslib/tslib.js:141:27)
error Command failed with exit code 1.
```

```
entity: User
items:
    user1:
        authEmail: me@domain.com
        auth.email: me@domain.com
        auth.Email: me@domain.com
        auth:
            authEmail: me@domain.com
        __call:
            auth.setPassword:
                - test
            auth.setEmailVerified:
                - true
```

```
@Entity()
export class User {
    @PrimaryGeneratedColumn('uuid')
    uuid?: string;

    @ValidateNested()
    @Column(() => LocalAuth)
    auth?: LocalAuth;
}
```

```
export abstract class LocalAuth {
    @IsEmail()
    @Index({unique: true})
    @Column({comment: 'email = username', unique: true})
    email?: string;

    @BeforeInsert()
    emailToLowerCase() {
        this.email = this.email?.toLowerCase();
    }

    @IsDate()
    @Column({nullable: true})
    email_verified_at?: Date;

    setEmailVerified(verified: boolean) {
        if (verified) {
            this.email_verified_at = new Date();
        } else {
            this.email_verified_at = undefined;
        }
        return this;
    }
}
```
