### ISSUE TITLE
[Bug] Cannot load fixture

### ISSUE THREAD

**Issue by rogeraraujo90** [RobinCK/typeorm-fixtures#155]
### Your Environment

| Software         | Version(s) |
| typeorm-fixtures-cli | 1.8.0 |
| Node             | 14.5.0
| Yarn         | 1.22.4
| Operating System | MacOs 10.15.7

I have the following relation:

- A Team entity
- A Source entity
- A News entity, that has ManyToOne relationship with Team and Source

```js
@ManyToOne(() => Source)
@JoinColumn({ name: "sourceId" })
source: Source;

@ManyToOne(() => Team)
@JoinColumn({ name: "teamId" })
team: Team;
```

- A Comment entity, that has ManyToOne relationship with a News and a Comment
```js
@ManyToOne(() => News)
@JoinColumn({ name: "newsId" })
news: News;

@ManyToOne(() => Comment)
@JoinColumn({ name: "parentId" })
parent: Comment | null;
```

I'm trying load some comments in database but, if all `News` have a `Team` then I get this error:

<img width="1387" alt="Screen Shot 2020-11-12 at 21 11 43" src="https://user-images.githubusercontent.com/6045678/99011808-aced8200-252b-11eb-8a52-2e860c031291.png">

If I leave some `News` without a `Team` then the fixtures are loaded. But the Comments are related just with the `News` without a `Team`.

Using a `console.log` I found that the `parse` method in `ReferenceParser` is been called with the `entities` without any news. So, probably the library is trying load the comments when there is no news created.

**Comment by RobinCK** [comment]
it's hard to say something without a yaml file

**Comment by rogeraraujo90** [comment]
Sorry,

The related yaml files:

- News:
```yaml
entity: News
items:
  new{1..5}:
    title: '{{random.words}}'
    subtitle: '{{lorem.words}}'
    summary: '{{lorem.text}}'
    url: '{{internet.url}}'
    image: '{{image.imageUrl}}'
    source: '@source*'
    team: '@team*'
    createdDate: '{{date.past}}'
    updatedDate: '{{date.recent}}'

  new{6..8}:
    title: '{{name.title}}'
    summary: '{{lorem.words}}'
    url: '{{internet.url}}'
    image: '{{image.imageUrl}}'
    source: '@source*'
    team: '@team*'
    createdDate: '{{date.past}}'
    updatedDate: '{{date.recent}}'
```

- Comments
```yaml
entity: Comment
processor: ./processors/CommentProcessor
items:
  comment{1..40}:
    text: '{{lorem.text}}'
    news: '@news*'
    author: '@user*'
    createdDate: '{{date.past}}'

  comment{41..50}:
    text: '{{lorem.text}}'
    parent: '@comment{1..40}'
    author: '@user*'
    createdDate: '{{date.recent}}'
```

With this content, I can't load the fixtures the error is shown in console. If I remove `team` from ` new{6..8}` works, and all comments are related with these news (without a team)
