### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by DanielMenke** [RobinCK/typeorm-fixtures#171]
### Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| typeorm-fixtures | 1.9.1
| Node             | 15
| npm/Yarn         | 1.22.5
| Operating System | Ubuntu

Hi there, thanks for this project. 

I am currently trying to integrate it in the tests of my nest project, but cant get it to work properly. 

When I try to get these fixtures 
```yaml
entity: Customer
items:
  customer1:
    company: '{{name.firstName}}'
    customerNumber: '{{datatype.number}}'
    baseFeeType: 'none'
    devices:
      - device1
  customer2:
    company: '{{name.firstName}}'
    customerNumber: '{{datatype.number}}'
    baseFeeType: 'monthly'
    devices:
      - device2
  customer3:
    company: '{{name.firstName}}'
    customerNumber: '{{datatype.number}}'
    baseFeeType: 'quarterly'
    devices:
      - device3
  customer4:
    company: '{{name.firstName}}'
    customerNumber: '{{datatype.number}}'
    baseFeeType: 'annually'
    devices:
      - device4
```
persisted to my test database with this code:

```typescript
describe('BillingService', () => {
  let service: BillingService;

  beforeEach(async () => {
    const module: TestingModule = await Test.createTestingModule({
      imports: [
        SessionModule,
        TypeOrmModule.forRoot(testConfig),
        TypeOrmModule.forFeature([Bill]),
      ],
      providers: [BillingService],
    })
      .overrideProvider(TwilioService)
      .useValue({})
      .compile();

    const app = module.createNestApplication();
    await app.init();
    service = module.get<BillingService>(BillingService);

    const loader = new Loader();
    loader.load(__dirname + '/fixtures');
    const resolver = new Resolver();
    const fixtures = resolver.resolve(loader.fixtureConfigs);

    const connection: Connection = module.get(Connection);
    const builder = new Builder(connection, new Parser());

    for (const fixture of fixturesIterator(fixtures)) {
      const entity = await builder.build(fixture);
      console.log(entity);
      await getRepository(entity.constructor.name).save(entity);
    }
  });

  it('should be defined', () => {
    expect(service).toBeDefined();
  });
});
```

the `console.log()` always prints `Customer {}`, which is the correct type of entity, but empty, meaning it does not contain any of the fields mentioned in the fixture yaml, which again crashes the `save` call, because the database restrictions are not fullfilled. 

Any suggestions what I can try to make it work?
