### ISSUE TITLE
[Feature request] "Scenario": load fixtures from a single file and which can extends each other 

### ISSUE THREAD

**Issue by alexstrat** [RobinCK/typeorm-fixtures#180]
I'm (programmatically) using `typeorm-fixtures` for integration testing: on `beforeEach` I load a fixtures folder to set my DB in a certain state (let's call it a "scenario") and run my tests against it.

Works well, but, along the path, I found the workflow a bit irritating because:
- difficult to have a **comprehensive view** of the desired DB scenario because the fixtures have to be disseminated in several files. Example: to have a scenario with a user completed profile and their post, the scenario information is in 3 files `User.yaml`, `Profile.yaml` and `Post.yaml`
- some scenarios have a lot in commons but I need to **duplicate** the whole fixtures folder for each scenario. Example: in a scenario A I have a user completed profile and their post; and in scenario B, I have a user completed profile and their comment on a post

Still along the path, I'm finally writing my scenarios in a scenario file that looks like this:
```yml
description:  A user completed profile and their comment on a Post
extends:
  - './base-user-with-profile.scenario.yaml'
fixtures:
  - entity: User
    items:
      writer:
        name: Walt
  - entity: Post
    items:
      post:
        user: '@writer'
        content: Awesome
  - entity: Comment
    items:
      user_post:
        user: '@user'
        content: Super post
```

It would be cool if this could inspire upcoming features!
