### ISSUE TITLE
[Bug] Null ID when referencing another fixture

### ISSUE THREAD

**Issue by tylergets** [RobinCK/typeorm-fixtures#202]
Hey there, I am having issues with the latest version of this library.

When I try and create a new instance of a child model, it is not receiving the ID of the referenced fixture. This results in the entity failing to save because of constraints.

For example:

```
error: Error: null value in column "locationId" violates not-null constraint
```

Here are my fixtures

```yaml
entity: Location
items:
  location1:
    name: '{{company.name}}'
    tenant: 'd1a5fcf3-08f6-4035-a766-6c7c9733c39a'
    flags: '[]'
```

and

```yaml
entity: Role
items:
  role1:
    name: '{{company.name}}'
    location: '@location1'
```

I am continuing to look further, however wanted to see if anyone else has ran into this.

| Software         | Version(s) |
| ---------------- | ---------- |
| typeorm-fixtures | 3.0.1
