### ISSUE TITLE
Problem with @Exclude

### ISSUE THREAD

**Issue by tdrapied** [RobinCK/typeorm-fixtures#212]
The `ignoreDecorators` argument does not seem to work with the @Exclude annotation (class-transformer) in the entity.

Is it possible to fix this?

For example:

```ts
@Entity()
export class Land {
  @PrimaryColumn()
  id: number;

  @Column()
  name: string;

  // List of land ids that are adjacent to this land
  @ApiHideProperty()
  @Exclude()
  @Column({ nullable: true, type: 'simple-json' })
  borders: Array<number>;
}
```

```yaml
entity: Land
items:
  land1:
    id: 1
    name: Forest
    borders:
      - 2
      - 3
```

**> Result: the `borders` fields are not defined.**

![image](https://user-images.githubusercontent.com/35509872/235313717-8fa06056-6640-4101-a75e-931f83c4e84f.png)
