### ISSUE TITLE
[Feature request] Add faker examples with parameters in README

### ISSUE THREAD

**Issue by picchi-lucas** [RobinCK/typeorm-fixtures#213]
As this lib is using [`faker.helpers.fake`](https://fakerjs.dev/api/helpers.html#fake) helper parameters can be used.
It would be great to have it mentioned in the README.

Example:
- Generate random [numeric string](https://fakerjs.dev/api/string.html#numeric) of length 4:

```yml
entity: MyEntity
items:
  myEntity1:
    randomNumericString:  '{{string.numeric({ length: 4 })}}'
```
