### ISSUE TITLE
[Feature request] Reference on field to generate another

### ISSUE THREAD

**Issue by picchi-lucas** [RobinCK/typeorm-fixtures#214]
Example:
- Generate an username
- Use the generated username to generate email

```yml
entity: User
items:
  user{1..10}:
    name: '{{person.firstName}}'
    lastName: '{{person.lastName}}'
    username: '{{internet.userName}}'
    email: '($username)@gmail.com'
```
