### ISSUE TITLE
How to use it with nullable self-referential relations?

### ISSUE THREAD

**Issue by gbirke** [RobinCK/typeorm-fixtures#64]
I have a category entity set up like in [the example](https://typeorm.io/#/relations-faq/how-to-create-self-referencing-relation) that optionally points to another category, creating a parent/child relationship. The topmost categories don't have a parent (so its parent attribute is nullable)

My fixture looks like this:

```yaml
entity: Category
items:
  category1:
    name: 'first'
    parent: null
    sortId: 1
```

I get an error when it tries to insert the fixture, because it tries to insert a second, empty category.

I've traced through the code to see what it's doing and it converts the `{parent:null}` from the fixture to an empty object `{parent: {}}` in the Entity.
