### ISSUE TITLE
reference own column in faker.helpers

### ISSUE THREAD

**Issue by mreschke** [RobinCK/typeorm-fixtures#65]
How can I reference the `title` of the current iteration to slugify it with faker.helpers.slugify.  I would expect something like so

```
entity: Post
items:
  post{1..10}:
    title: '{{lorem.words}}'
    slug: '{{helpers.slugify(@title)}}'
    body: '{{lorem.paragraphs}}'
```
