### ISSUE TITLE
ManyToMany Relations error

### ISSUE THREAD

**Issue by kop7** [RobinCK/typeorm-fixtures#67]
`"typeorm-fixtures-cli": "^1.3.5"`
 
Getting error when run fixtures Ads.yml:

`Fail fixture loading: Entity metadata for Category#ads was not found.`

maybe is bug? 

```ts 
@Entity('ad')
export class Ad {
  @PrimaryGeneratedColumn
  id: number;
  @Column()
  title: string;
  @ManyToMany(type => Category, category => category.ads)
  @JoinTable({ name: 'ad_category' })
  categories: Category[];
}
 ````

```ts
@Entity('category')
export class Category {
  @PrimaryGeneratedColumn()
  id: number;
  @Column)
  name: string;
  @ManyToMany(type => Ad, ad => ad.categories)
  ads: Ad[];
}
 ```

Ads.yml

```yml
entity: Ad
items:
  ad{1..100}:
    title: '{{name.jobType}}'
    categories:
      category1:
        name: '{{name.jobArea}}'
```
