### ISSUE TITLE
Set Relations in Processor

### ISSUE THREAD

**Issue by spech66** [RobinCK/typeorm-fixtures#92]
It would be very nice to be able to set references in the processor to allow more complex assignments of the relations. It would also be nice to have access to $current in the processor without extracting it from `name` parameter. This would allow things like:

```
items:
  a1:
    order: '0'
    parent: '@p1'
  a2:
    order: '1'
    parent: '@p1'
  a3:
    order: '2'
    parent: '@p1'
  a4:
    order: '3'
    parent: '@p1'
  a5:
    order: '4'
    parent: '@p1'
  a6:
    order: '0'
    parent: '@p2'
```

to be replaced by 
```
processor:
object.order = current % 5;
object.parent = `@p${current%5}`;


items:
  a{1..1}:
```
