### ISSUE TITLE
Extra fields in Users entity

### ISSUE THREAD

**Issue by ishpartko** [RobinCK/typeorm-fixtures#99]
when I set data for Users entity I got extra fields in DB
My Users entity:
```ts
import { Column, Entity, PrimaryGeneratedColumn } from "typeorm";

@Entity()
export class Users {
  @PrimaryGeneratedColumn()
  id: number;

  @Column({ length: 100 })
  name: string;
}
```
I got:
![изображение](https://user-images.githubusercontent.com/27618114/74041576-f32f1700-49d6-11ea-9fb3-837b16940371.png)

**With other entities all good, but not with this**. What can it be?

**Comment by ishpartko** [comment]
// Users.yml
```yml
entity: Users
parameters: {}
items:
  users1:
    name: 'admin'
```
